= Spring MVC Cache Control

image:https://github.com/mihxil/spring-mvc-cache-control/actions/workflows/maven.yml/badge.svg[Build Status,link=https://github.com/mihxil/spring-mvc-cache-control/actions/workflows/maven.yml] 
image:https://img.shields.io/maven-central/v/org.meeuw.spring/spring-mvc-cache-control.svg?label=Maven%20Central[Maven Central,link=https://central.sonatype.com/search?q=a%3Aspring-mvc-cache-control]
image:https://codecov.io/gh/mihxil/spring-mvc-cache-control/branch/main/graph/badge.svg?token=EDs91Mcwem[codecov,link=https://codecov.io/gh/mihxil/spring-mvc-cache-control]
image:https://img.shields.io/nexus/s/https/oss.sonatype.org/org.meeuw.spring/spring-mvc-cache-control.svg[snapshots,link=https://oss.sonatype.org/content/repositories/snapshots/org/meeuw/spring/spring-mvc-cache-control/]
image:http://www.javadoc.io/badge/org.meeuw.spring/spring-mvc-cache-control.svg?color=blue[javadoc,link=http://www.javadoc.io/doc/org.meeuw.spring/spring-mvc-cache-control]
 

Spring MVC Cache Control is an extension to http://static.springsource.org/spring/docs/current/spring-framework-reference/html/mvc.html[Spring MVC] that aims to simplify implementing HTTP/1.1 Cache-Control headers for annotated MVC controllers.

== Introduction

This was forked from  foo4u/spring-mvc-cache-control.

In 2024, I revived my fork, because the original maintainer is not maintaining it anymore and: 

- updated spring (to 6)
- updated java (to 17)
- updated servlet-api (to 6) (`jakarta.servlet`)
- dropped gradle (I'm sorry, It didn't work)
- added github actions for the build
- resolved the outstanding reported issues
- published it to maven central and sonatype with new coordinates

== Usage

=== Add Spring MVC Cache Control to Your Project.

==== Maven Projects

----
<dependency>
    <groupId>org.meeuw.spring</groupId>
    <artifactId>spring-mvc-cache-control</artifactId>
    <version>2.0</version>
</dependency>
----

==== Gradle Projects

----
compile 'org.meeuw.spring:spring-mvc-cache-control:2.0'
----

=== Configuration

Simply include `net.rossillo.spring.web.mvc.CacheControlHandlerInterceptor` in your Spring MVC configuration.

==== XML Web Application Context

----
<mvc:interceptors>
    <bean class="net.rossillo.spring.web.mvc.CacheControlHandlerInterceptor" />
</mvc:interceptors>
----

_For XML contexts, this usually defaults to `${appName}-servlet.xml`_

==== Java Web Application Context

----
@Configuration
public class WebMvcConfig extends WebMvcConfigurerAdapter implements WebMvcConfigurer
{
    @Override
    public void addInterceptors(InterceptorRegistry registry)
    {
        registry.addInterceptor(new CacheControlHandlerInterceptor());
    }
}
----

=== Annotate Your Controllers

Use the `@CacheControl` annotation on either (or both) type level `@Controller`s or method level `@RequestMapping`s. The handler interceptor will read the annotations and generate HTTP/1.1 compliant cache-control headers. For example:

----
@Controller
public final class DemoController {

	/**
	 * Public home page, cacheable for 5 minutes.
	 */
	@CacheControl(maxAge = 300)
	@RequestMapping({"/", "/home.do"})
	public String handleHomePageRequest(Model model) {
		...
	}
}
----

See our https://github.com/foo4u/spring-mvc-cache-control/blob/master/spring-mvc-cache-control-demo/src/main/java/net/rossillo/spring/web/mvc/demo/DemoController.java[spring-mvc-cache-control-demo] project for full details.

== Building from Source

. Clone the repository from GitHub:
+
----
$ git clone git://github.com/mihxil/spring-mvc-cache-control
----

. Navigate into the cloned repository directory:
+
----
$ cd spring-mvc-cache-control
----

. The project uses maven to build:
+
----
$ mvn
----

== IDE Integration

=== IntelliJ IDEA

IDEA natively support maven projects. Simply choose to import an existing project and select
the `pom.xml` file. 


== Contributing

Contributions are always welcome. Fork the repository, create a topic branch and send a pull request.
